language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mariusble/docker-react -f ./client/Dockerfile.dev ./client

script:
#  - docker run mariusble/docker-react npm run test -- --coverage
  - docker run -e CI=true mariusble/docker-react npm run test

after_success:
  - docker build -t mariusble/multi-client ./client
  - docker build -t mariusble/multi-nginx ./nginx
  - docker build -t mariusble/multi-server ./server
  - docker build -t mariusble/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 

  - docker push mariusble/multi-client
  - docker push mariusble/multi-nginx
  - docker push mariusble/multi-server
  - docker push mariusble/multi-worker


#deploy:
#  provider: elasticbeanstalk
#  region: "eu-west-3"
#  app: "docker-react"
#  env: "DockerReact-env"
#  bucket_name: "elasticbeanstalk-eu-west-3-015249056795"
#  bucker_path: "docker-react"
#  on:
#    branch: master 
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"
